os: linux
sudo: required
language: php

services:
  - mysql
  - postgresql

php:
  - 5.4
  - 7
 
env:
  - DB=sqlite
  - DB=mysql
  - DB=pgsql

install:
  - sudo apt-get install -qq apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - if [ -d ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d ]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f test/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - curl 'http://localhost'
