os: linux
sudo: false
language: php

services:
  - mysql
  - postgres

php:
  - 5.4
  - 5.6
  - 7.0
 
env:
  - DB=sqlite
  - DB=mysql
  - DB=pgsql

install:
  - sqlite3

before_script:
  - true

script:
  - true
