<?php
// version-indepenent configuration variables
require_once("basefuncs.php");

// read the configuration values from a nearby location
$cfgPath = "/etc/dl.php";
foreach(explode(PATH_SEPARATOR, get_include_path()) as $path)
{
  $tmp = "$path/config.php";
  if(is_file($tmp))
  {
    $cfgPath = $tmp;
    break;
  }
}
require_once($cfgPath);

// variables
if(!isset($defLocale)) $defLocale = "en_US";
if(!isset($cfgVersion)) $cfgVersion = "0.4";
if(!isset($phpExt)) $phpExt = ".php";
if(!isset($maxSize)) $maxSize = ini_get('upload_max_filesize');
if(!isset($authReal)) $authRealm = "Restricted Area";
if(!isset($sessionName)) $sessionName = "DL" . md5($masterPath);
if(!isset($dsn)) $dsn = "sqlite:$spoolDir/data.sdb";
if(!isset($gcProbability)) $gcProbability = 1.0;
if(!isset($gcInternal)) $gcInternal = true;
if(!isset($gcLimit)) $gcLimit = 0;
if(!isset($defaultTotalDays)) $defaultTotalDays = 7;
if(!isset($defaultLastDl)) $defaultLastDl = 24;
if(!isset($defaultMaxDl)) $defaultMaxDl = 0;

// derived data
$useSysLog = (!empty($logFile) && strstr($logFile, "/") === FALSE);
$iMaxSize = returnBytes($maxSize);
$dataDir = $spoolDir . "/data";
$adminPath = $masterPath . "admin$phpExt";
$helpRoot = "static/guide";
$dPath = $masterPath . "d$phpExt";
$rPath = $masterPath . "rest$phpExt";

// constants
$dlVersion = "0.10";
$bannerUrl = 'http://www.thregr.org/~wavexx/software/dl/';
$banner = 'Generated by <a href="' . htmlentities($bannerUrl) . '">dl ticket service</a>';
$cookieLifetime = 1000 * 60 * 60 * 24 * 90;
$maxUUTries = 32;
