<?php
$title = 'Login Form';
includeTemplate('style/include/header.php', compact('title'));
?>

<div class="form_description">
  <h2><?=$title?></h2>
  <p>dl: minimalist download ticket service</p>
</div>

<form action="<?php echo $masterPath; ?>" method="post">
  <ul >
    <!--
    <li>
      <label class="description">Username</label>
      <div>
	<input name="p" class="element text medium" type="password" maxlength="25"/>
      </div><p class="guidelines"><small>Type in the password to access the filesharing service.</small></p>
    </li>
    -->

    <li>
      <label class="description">Password</label>
      <div>
	<input name="p" class="element text medium" type="password" maxlength="25"/>
      </div><p class="guidelines"><small>Type in the password to access the filesharing service.</small></p>
    </li>

    <li class="buttons">
      <input id="saveForm" type="submit" name="submit" value="Login"/>
    </li>
  </ul>
</form>

<div id="footer">
  Generated by <a href="http://www.thregr.org/~wavexx/hacks/dl/">dl ticket service</a>
</div>

<?php
includeTemplate('style/include/footer.php');
?>
